// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string;
  header: string;
  logo: string;
  burgerBlock: string;
  burger: string;
  text: string;
  textOrange: string;
}
export const cssExports: CssExports;
export default cssExports;
