// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string;
  header: string;
  logo: string;
  burgerBlock: string;
  burger: string;
  text: string;
  textOrange: string;
  textFooter: string;
  footer: string;
  logoFooter: string;
  footerBlocks: string;
  logoText: string;
  links: string;
  textFooterBold: string;
  number: string;
}
export const cssExports: CssExports;
export default cssExports;
